FROM alpine:latest
MAINTAINER Gustavo Henrique [gustavohenrique.net]

RUN apk add --update bash shadow openssh-server-pam openssh-sftp-server && \
    rm -rf /var/cache/apk/* && \
    ln -snf /usr/sbin/sshd.pam /usr/sbin/sshd && \
    mkdir -p /var/run/sshd && \
    rm -f /etc/ssh/ssh_host_*key*

COPY files/sshd_config /etc/ssh/sshd_config
COPY files/create-sftp-user /usr/local/bin/
COPY files/entrypoint /

EXPOSE 22

ENTRYPOINT ["bash", "/entrypoint"]
