FROM postgres:16-alpine

ENV PG_PARTMAN_VERSION v5.2.4
ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8
ENV TZ_DATA=America/Sao_Paulo

RUN set -ex \
    && apk add --update --no-cache \
        tar \
        autoconf \
        automake \
        g++ \
        clang-dev \
        llvm \
        libtool \
        libxml2-dev \
        make \
        perl \
        musl-locales \
    && wget -O pg_partman.tar.gz "https://github.com/pgpartman/pg_partman/archive/$PG_PARTMAN_VERSION.tar.gz" \
    && mkdir -p /usr/src/pg_partman \
    && tar \
        --extract \
        --file pg_partman.tar.gz \
        --directory /usr/src/pg_partman \
        --strip-components 1 \
    && rm pg_partman.tar.gz \
    && cd /usr/src/pg_partman \
    && make \
    && make install \
    && rm -rf /usr/src/pg_partman /var/cache/apk/* \
    && apk del llvm automake autoconf clang-dev make

COPY ./pg_partman_initdb.sh /docker-entrypoint-initdb.d/initdb.sh
