pg_partman:
	@docker build . -f Dockerfile-pg_partman -t=gustavohenrique/postgresql-pgpartman:16

pg_partman_alpine:
	@docker build . -f Dockerfile-pg_partman-alpine -t=gustavohenrique/postgresql-pgpartman:16-alpine
